### ISSUE TITLE
Nuclide run-through #2

### ISSUE THREAD

**Issue by vjeux** [jlongster/prettier#6]
Since the first one went really well, let's do another round :)

The issues are getting more scoped and less serious :)

- [x] Should put the arrow function body on the next line instead of breaking it in weird ways

![image](https://cloud.githubusercontent.com/assets/197597/21739260/776386f0-d44b-11e6-84d9-d93ee8d7b014.png)

- [ ] I think I like the arrow function better for type

![image](https://cloud.githubusercontent.com/assets/197597/21739271/c9bce8ba-d44b-11e6-9072-eaf5daca0730.png)

- [x] Would be nice to make empty body have the `}` on their own line

![image](https://cloud.githubusercontent.com/assets/197597/21739279/062adc80-d44c-11e6-8bb7-5e0768f3ddde.png)

- [x] Space before would be nice

![image](https://cloud.githubusercontent.com/assets/197597/21739282/11b60eee-d44c-11e6-8ca2-2e07ab216d4b.png)

- [ ] Wrong code generated because of comment placement

![image](https://cloud.githubusercontent.com/assets/197597/21739285/436b9b52-d44c-11e6-8159-5072ff4c102d.png)

- [x] Invalid code generated because of trailing comma

![image](https://cloud.githubusercontent.com/assets/197597/21739292/716867b0-d44c-11e6-9c84-ee5c3dc0c584.png)

- [ ] Would be nice to keep the comment where it was

![image](https://cloud.githubusercontent.com/assets/197597/21739304/b0d17ed2-d44c-11e6-988c-286ed4d16f21.png)

- [x] If one `&&` is broken, would be nice to break all of them into their own line

![image](https://cloud.githubusercontent.com/assets/197597/21739313/e488767c-d44c-11e6-9a30-703ed549dbdb.png)

- [x] Missing type annotation for argument spread

![image](https://cloud.githubusercontent.com/assets/197597/21739319/16411a8e-d44d-11e6-9b6e-ae1c3c0f5cee.png)

- [x] Missing `;` for export default

![image](https://cloud.githubusercontent.com/assets/197597/21739331/437ae6ba-d44d-11e6-8238-53a248cb215c.png)

- [x] Missing parenthesis for ++

![image](https://cloud.githubusercontent.com/assets/197597/21739340/76108a4e-d44d-11e6-863e-16a7057268e5.png)

- [x] Missing generic

![image](https://cloud.githubusercontent.com/assets/197597/21739343/7fc225e8-d44d-11e6-88dc-0be1915f08a8.png)

- [x] Import doesn't break

![image](https://cloud.githubusercontent.com/assets/197597/21739349/b0e448f4-d44d-11e6-8e4d-acdd3794d49d.png)

**Comment by jlongster** [comment]
Thanks! Yeah, comments are pretty buggy right now. I removed a bunch of logic from recast because I need to convert it to my new API, so still need to do that. I think it's very difficult to keep comments exactly where they are, but we'll see what we can do.

I'm going to focus mostly on your first run-through before announcing it next week. It would be great if others began picking up some of the smaller tweaks and opened PRs after that. It may be good to break this one up into individual issues so that's easier.

**Comment by jlongster** [comment]
> Should put the arrow function body on the next line instead of breaking it in weird ways

This was because of the last arg grouping. It's an anon function so it lets it break itself. However I think it makes sense to only allow that if it's an arrow function with braces. I fixed this in https://github.com/jlongster/jscodefmt/commit/892d07031314b0e353af35601491db659328f802

**Comment by jlongster** [comment]
> I think I like the arrow function better for type

I'd like more feedback from Flow users... I think I got this logic from recast. I believe it's easy to tweak if we do want this.

**Comment by jlongster** [comment]
> Would be nice to make empty body have the } on their own line

I like the empty block :) These are small diffs, do you think little diffs like that will make it a lot harder for you to pitch this?

For things like like this I would like more feedback from the community, but I also want to prioritize helping make this work for you. I think getting it work on nuclide is a strong use case and I'm fine tweaking the defaults to make that work.

**Comment by jlongster** [comment]
> Invalid code generated because of trailing comma

Looks like this was already fixed by another commit

**Comment by vjeux** [comment]
> I like the empty block :)

Cool, that's good. There aren't many empty blocks in real world anyway :p

**Comment by jlongster** [comment]
> Cool, that's good. There aren't many empty blocks in real world anyway :p

I may have just convinced myself that maybe it's better to split them across 2 lines because then it's easier to add code to them... but this can easily be changed later.

**Comment by slobo** [comment]
> > Cool, that's good. There aren't many empty blocks in real world anyway :p

> I may have just convinced myself that maybe it's better to split them across 2 lines because then it's easier to add code to them... but this can easily be changed later.

```} catch (err) {}```

should format to

```} catch (and_ignore_err) {}```

only half joking...

**Comment by karl** [comment]
>> Invalid code generated because of trailing comma
> Looks like this was already fixed by another commit

Do you have a link to the commit that fixes this? I'm still seeing it on version `0.0.4`. This code:

```
const LongVariableName = longMethodName(longParamName, longSecondParamName, () => {});
```

becomes:

```
const LongVariableName = longMethodName(longParamName, longSecondParamName, (
  ,
) => 
  {});
```

Which is invalid as the comma is inside the empty parameter list.

https://vjeux.github.io/prettier-browser/#%7B%22content%22%3A%22const%20LongVariableName%20%3D%20longMethodName(longParamName%2C%20longSecondParamName%2C%20()%20%3D%3E%20%7B%7D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22useFlowParser%22%3Afalse%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Afalse%7D%7D

**Comment by jlongster** [comment]
Yeah, there's another bug about that too. I'll look into it.

**Comment by vjeux** [comment]
Just sent #133 and #134 for the types that didn't print on babylon parser.

**Comment by vjeux** [comment]
Closing this one, most of those are either done or already have open issues!
